Feature add repr to object classes
christiansandberg/canopen pull request #432
Opened 2024-05-14 16:58 UTC by sveinse

A common usage pattern is to work with *object* classes, which include `*Variable()`, `*Array()` and `*Record()`. Currently the object is printed without any more useful info that its address. This PR adds a richer output for the objects (albeit without address) making it easier to develop. It prints the object name and the index and subindex

```xml
# Currently
<ODVariable object at 0x0000023929209B20>

# New OD
<ODVariable 'Device Type' at 0x1000>   # No subindex
<ODVariable 'RTC.DateTime' at 0x2020:01>   # With subindex
<ODArray 'Power bus enabled' at 0x2012>
<ODRecord 'LED' at 0x2030>

# New SDO
<SdoVariable 'Device Type' at 0x1000>
<SdoArray 'Power bus enabled' at 0x2012>
<SdoRecord 'LED' at 0x2030>

# New PDO
<PdoMap 'RxPDO1_node1' at COB-ID 0x513>
<PdoVariable 'RTC.BCD DateTime' at 0x2020:02>
```

(The main motivation for PR #431 was to be able to print `<PdoMap...`  and not just `<Map...`)

While writing this PR I noticed an interesting inconsistency in `*Variable()`. The `obj.name` attribute in `SdoVariable()` and `PdoVariable()` for subindex variable instances contains their parent names:

    Battery.Battery Level   # Example object name var.name

However, `ODVariable()`, differs from this: It contains only `Battery Level` and not prefixed by the parent object. It was tempting to alter the behavior for `ODVariable` and ensure the `.name` field is handled equally and consistently across all variants, but I did not.  It will break current behavior and it meddles with how OD import/export is made. I chose to implement a new property `ODVariable.qualname` much akin to how Pythons class `__qualname__` is used. This attr is used from `__repr__()` to achieve consistent printing on all variable variants.

2024-05-14 17:34 UTC, erlend-aasland reviewed
Style nit.

2024-05-14 17:34 UTC, erlend-aasland commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} '{self.name}' at 0x{self.index:04x}>"
```suggestion
        return f"<{type(self).__qualname__} {self.name!r} at 0x{self.index:04x}>"
```

2024-05-14 17:34 UTC, erlend-aasland commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} '{self.name}' at 0x{self.index:04x}>"
```suggestion
        return f"<{type(self).__qualname__} {self.name!r} at 0x{self.index:04x}>"
```

2024-05-14 17:34 UTC, erlend-aasland commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} '{self.qualname}' at 0x{self.index:04x}{suffix}>"
```suggestion
        return f"<{type(self).__qualname__} {self.qualname!r} at 0x{self.index:04x}{suffix}>"
```

2024-05-14 17:46 UTC, sveinse commented
Style nit updated. Thanks @erlend-aasland . <-- I learned a new py formatter today. Awesome 🥳

2024-05-14 18:03 UTC, erlend-aasland reviewed
Oh, I forgot you can use the `#` [format specifier](https://docs.python.org/3/library/string.html#format-specification-mini-language) to get the `0x` prefix! ~~It won't save any characters, but~~ It saves you _one_ character, and it is slightly neater.

2024-05-14 18:03 UTC, erlend-aasland commented on canopen/variable.py
> +        return f"<{type(self).__qualname__} {self.name!r} at 0x{self.index:04x}{suffix}>"
```suggestion
        return f"<{type(self).__qualname__} {self.name!r} at {self.index:#04x}{suffix}>"
```

2024-05-14 18:10 UTC, sveinse commented
> Oh, I forgot you can use the `#` [format specifier](https://docs.python.org/3/library/string.html#format-specification-mini-language) to get the `0x` prefix! ~It won't save any characters, but~ It saves you _one_ character, and it is slightly neater.

Yes, I am aware. Muscle memory is an odd thing. I worked on a project where we needed "0xABCD" and `{x:#04X}` can't provide that so we had to do it with `0x{x:04X}`. And now much later the it's stuck 🌞

2024-05-14 18:25 UTC, erlend-aasland commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} {self.qualname!r} at 0x{self.index:04x}{suffix}>"
Would it make sense to print `suffix` in hex (without the `0x` prefix of course) as well?

2024-05-14 18:26 UTC, erlend-aasland commented
> I worked on a project where we needed "0xABCD" and `{x:#04X}` can't provide that so we had to do it with `0x{x:04X}`.

Right, because `#04X` would give you the `0X` prefix instead of `0x`. That's ... irritating 😄 Well, it's too late to change that in Python; it would be a breaking change. Somewhere in the world, there is production code that depends on that exact format being produced 🤷

But, we're way off-topic for this PR. The change looks good with or without the `#` specifier. (I added one more remark regarding `suffix` in https://github.com/christiansandberg/canopen/pull/432#discussion_r1600473733.)

2024-05-14 19:50 UTC, sveinse commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} {self.qualname!r} at 0x{self.index:04x}{suffix}>"
Uncertain. Having e.g. `0x2000:0x34` is very formally precise, but its a bit cluttered IMHO.

2024-05-14 22:19 UTC, acolomb commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} {self.qualname!r} at 0x{self.index:04x}{suffix}>"
From my experience, it seems customary to leave out the second `0x` prefix, but stay in hexadecimal nonetheless. Think of it as a 24 bit number with the colon just marking the border between index and subindex.

Thus I'd prefer `f'0x{index:04X}:{sub:02X}'`, which I use myself and have seen in the majority of CANopen documentation.

2024-05-14 22:47 UTC, erlend-aasland commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} {self.qualname!r} at 0x{self.index:04x}{suffix}>"
Yes, as stated in https://github.com/christiansandberg/canopen/pull/432#discussion_r1600473733, I definitely suggest to leave out the prefix; my question was if it should be printed in hex or decimal. I'm aligned to the former:

```suggestion
        return f"<{type(self).__qualname__} {self.qualname!r} at {self.index:#04x}{suffix:02x}>"
```

2024-05-14 22:47 UTC, erlend-aasland commented on canopen/variable.py
> +        return f"<{type(self).__qualname__} {self.name!r} at 0x{self.index:04x}{suffix}>"
```suggestion
        return f"<{type(self).__qualname__} {self.name!r} at {self.index:#04x}{suffix:02x}>"
```

2024-05-15 04:55 UTC, acolomb commented on canopen/objectdictionary/__init__.py
> +        return f"<{type(self).__qualname__} {self.qualname!r} at 0x{self.index:04x}{suffix}>"
Looks OK, but I think it's more common to use hexadecimal numbers printed with uppercase digits in CANopen context (e.g. in the specification). That's why the prefix should be printed manually (lowercase) and then both numbers in hex uppercase.

2024-05-15 13:08 UTC, erlend-aasland commented
I still think `suffix` should be represented in hex, not decimal.

2024-05-15 13:17 UTC, sveinse commented
> I still think `suffix` should be represented in hex, not decimal.

It is, isn't it?

2024-05-16 02:32 UTC, erlend-aasland commented
> It is, isn't it?

Ah, you're correct; I mistook it for an int. Sorry for the noise!

2024-05-16 02:32 UTC, erlend-aasland approved these changes

2024-05-16 08:36 UTC, acolomb requested changes

2024-05-16 10:30 UTC, sveinse commented on canopen/pdo/base.py
> +        return f"<{type(self).__qualname__} {self.name!r} at COB-ID 0x{self.cob_id:X}>"
@erlend-aasland perhaps you can chime in why `!r` is suitable here? I saw it as an opportunity to avoid using quotes in the f-string.

2024-05-16 11:35 UTC, erlend-aasland commented on canopen/pdo/base.py
> +        return f"<{type(self).__qualname__} {self.name!r} at COB-ID 0x{self.cob_id:X}>"
To clarify:

```python
>>> s = "thing"
>>> f"'{s}'"
"'thing'"
>>> f"{s!r}"
"'thing'"
>>> f"'{s}'" == f"{s!r}"
True
```

2024-05-16 15:10 UTC, acolomb commented on canopen/objectdictionary/__init__.py
> +    def qualname(self) -> str:
I'm okay with having it only here.  It's purely for internal use right now.

2024-05-16 15:10 UTC, acolomb approved these changes

2024-05-16 15:15 UTC, merged