Fix SDO writes of empty strings.
christiansandberg/canopen pull request #551
Opened 2024-11-25 17:51 UTC by willson556

Previously, when attempting a write of `""` to a `VISIBLE_STRING`, the expedited SDO request would not be sent and the transaction would timeout.

I traced this down to the `BufferedWriter` not issuing a write to the underlying stream when it has only been called with `b""`.

To resolve this, if the transaction size is known to be `0`, the `raw_stream` is now returned. I also added a unit test to cover this case.

2024-11-25 20:40 UTC, acolomb requested changes
Nice find and good job in fixing it.  Some nit-picks, but nothing serious that would keep this from being merged.

2024-11-25 20:53 UTC, sveinse commented on canopen/sdo/client.py
> +                # Therefore, skip the BufferedWriter if size is known to be 0
Can I also suggest that the comment here is not very clear (I had to read it twice and read the code to get it). Perhaps have it say something more concise like "BufferedWriter will omit the write if size is 0. For size 0 use the raw stream to ensure the message is sent."

2024-12-17 19:37 UTC, willson556 commented on test/test_sdo.py
> +            (TX, b'\x33\x00\x20\x00\x00\x00\x00\x00'),
Good catch! There are only 2 bits allocated to store `n`, and `n` would need to be 4, so this is spilling into a reserved bit. Looks like more digging is required here -- we may need to do a segmented transfer in the size == 0 case.

2024-12-17 20:21 UTC, willson556 commented on test/test_sdo.py
> +            (TX, b'\x33\x00\x20\x00\x00\x00\x00\x00'),
yeah, an empty expedited transfer is not possible. An empty segmented transfer is possible, switched to that.

2024-12-17 22:07 UTC, acolomb commented on test/test_sdo.py
> +            (TX, b'\x33\x00\x20\x00\x00\x00\x00\x00'),
Yes, an expedited download cannot have a specified size of 0 bytes.  It has either between 4-3=1 and 4-0=4 data bytes, or no size specified at all (s=0).  In the latter case, the object type decides how much of the data will be used, but with STRING I guess it's undefined how many bytes should be considered without a size indicated.

In essence, I agree that doing a segmented download is the better approach in this case.

2025-01-05 21:58 UTC, acolomb approved these changes

2025-01-05 22:01 UTC, merged